### ISSUE TITLE
SHA256 issues (and <<~EOS)

### ISSUE THREAD

**Issue by iainhouston** [hhu-stups/homebrew-prob#2]
`brew install hhu-stups/prob/prob` results in 

    Error: SHA256 mismatch
    Expected: dcf11c6d14c7deae0272c5102953f5ae4151f08b108923673a41af4a1276e6d7
    Actual: f78683fb6db33e8607e7d92a8ef9084c537c19fa8349138236f0e392b1e3b4be
    Archive: /Users/iainhouston/Library/Caches/Homebrew/prob-1.7.1.tar.gz

`brew install hhu-stups/prob/prob-nightly` results in  

    Warning: Cannot verify integrity of prob-nightly-20180226.tar.gz
    A checksum was not provided for this resource
    For your reference the SHA256 is:      
     bb0ffd8307ab04798326ada8b1686ce138ac2d856e7dd1c685a87f4960b1cec5
    Warning: Could not fix libz3.dylib in /usr/local/Cellar/prob-nightly/20180226/libexec/lib/z3interface.bundle
    Warning: Calling <<-EOS.undent is deprecated!
    Use <<~EOS instead.
    /usr/local/Homebrew/Library/Taps/hhu-stups/homebrew-prob/prob-nightly.rb:33:in `caveats'
    Please report this to the hhu-stups/prob tap!

**Comment by chegJH** [comment]
same here

**Comment by bivab** [comment]
Thanks for reporting, prob and prob-nightly should work using the latest version of this repository.
